version: '3.9'

networks:
  dev:
    driver: bridge

services:
  server:
    image: docker.io/library/violationwebapp
    container_name: violationwebapp_services
    ports:
      - 8080:80
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - dev
    depends_on:
      - violationwebapp-db

  violationwebapp-db:
    image: postgres:latest
    container_name: violationwebapp-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=violationwebapp
    ports:
      - 5432:5432
    networks:
      - dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d violationwebapp"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    volumes:
      - app_data:/var/lib/postgresql/data
  
volumes:
  app_data:



